РК 2
java-park-mail-ru/SeaBattle-09-2017 pull request #14
Opened 2017-10-19 13:26 UTC by KSolovyev

2017-10-22 12:49 UTC, isopov commented
Упс, я тут, оказывается, еще ничего не писал.

1. Зачем переопределяете наследуемые версии H2 & Postgres-драйвера?
2. `src/test/resources/db/migration/V1__init.sql` & `src/main/resources/db/migration/V1__init.sql` совпадают - если тестовый удалить, то миграции будут использоваться комбинированные из основных ресурсов и тестовых.
3. `src/test/resources/application.properties` - всё содержимое можно безболезненно удалить, автоконфигурация, когда видит H2 базу в classpath делает вам практически то же самое.
4. В основных application.properties:
- `spring.datasource.type=com.zaxxer.hikari.HikariDataSource` - нужно на spring-boot версии меньше 2 (у вас уже 2.0.0.M4 - кстати, почему бы не обновить до 2.0.0.M5?), когда в classpath кроме Hikari есть еще и tomcat-pool - у вас через spring-boot-starter-jdbc подтягивается в зависимости только Hikari
- `spring.datasource.driver-class-name=org.postgresql.Driver` - в боевой сборке у вас единстенный драйвер, да даже если бы это было и не так, то драйвер был бы понятен по урлу - строчка не нужна.
- `spring.datasource.hikari.maximum-pool-size=10` - конфиг совпадающий с конфигом по-умолчанию выглядит странно. Ну и вам почти наверняка нужно меньше.
5. `System.out.println` - в коде такого быть не должно - если нужно, пользуется логированием.
6. `private RowMapper<UserView> readUser` - вполне может быть `private static final`
7. ВАЖНО - пароли в базе хранить открытым текстом нельзя. Их нужно хешировать - https://park.mail.ru/blog/topic/view/7197/
8. `@Transactional @SpringBootTest(webEnvironment = RANDOM_PORT)` не работает - я вам на РК объяснял почему.
9. Привыкайте использовать параметризованные типы, вместо raw-типов везде, где это возможно - `HttpEntity<UserView>` вместо `HttpEntity`, `ResponseEntity<String>` вместо `ResponseEntity`. С моей точки зрения это важнее, чем все локальные переменные объявлять final (хотя это тоже можно - я так 2 года последние программировал)
10. Класс UserQueries всё-таки выглядит очень странно. Почему это не могут быть строчке прямо в тех местах, где они используются, я так и не понял.

2017-10-22 12:50 UTC, isopov requested changes
Замечания в комментарии.

2017-10-26 15:31 UTC, vla-parfenkov commented
Замечания исправлены.

2017-10-29 14:13 UTC, KSolovyev commented
@isopov ?

2017-10-31 09:37 UTC, isopov commented
1. Зачем переопределяете наследуемые версии H2 & Postgres-драйвера?
2. Привыкайте использовать параметризованные типы...
3. `@Bean` - аннотация означает, что метод создаёт объект для помещения его в спринговый контекст, но она должна быть в классе, помеченном `@Configuration` (или родственной аннотацией, например - `@SpringBootApplication`). У вас этот метод в контроллере просто каждый раз при вызове создаёт новый шифровальщик паролей.

А в общем, нормально - можно это пофиксать и к следующему РК...

2017-10-31 09:40 UTC, merged