РК 3
java-park-mail-ru/SeaBattle-09-2017 pull request #19
Opened 2017-11-27 22:25 UTC by vla-parfenkov

Думаем мы готовы к ревью
1. Есть мультиплеер
2. Интегрировано с фронтом
3. Есть тесты на геймлогику
4. Написан бот , но он пока не протестирован и не "подключен"

2017-11-29 13:29 UTC, KSolovyev commented
а можно в заголовок ПР ссылку на фронт?

2017-11-29 13:59 UTC, vla-parfenkov commented
Не хочет в заголовок как ссылкой вставляться, вставил в первый comment

2017-11-29 14:04 UTC, vla-parfenkov commented
Там на фронте мы не  помечаем клетки как блокированые вокруг корабля, после уничтожения. Но на сервере мы помечаем, поэтому играть неудобно, так как пользователь тыкает в клетку(которая на серваке заблочена) и не понимает, почему ничего не происходит. Но это будет исправлено.

2017-11-30 08:11 UTC, KSolovyev commented
у меня сессия самопроизвольно закрылась. Хотя я был в процессе расстановки корабликов

2017-11-30 08:12 UTC, KSolovyev commented
И вообще,  вывод дебажных сообщений алертом - это треш. Окончание, пока, можно оставить алертом, а остальное пишите в консоль

2017-11-30 08:39 UTC, KSolovyev requested changes

2017-11-30 08:39 UTC, KSolovyev commented on src/main/java/seabattle/game/field/Field.java
> +                throw new IllegalArgumentException("Given position is already checked!");
а если я очень быстро кликну два раза, то будет 500-ка и соединение отвалится? =)

2017-11-30 08:39 UTC, KSolovyev commented on src/main/java/seabattle/game/gamesession/GameSessionService.java
> +        Integer secondPlayerPosition = ThreadLocalRandom.current().nextInt(0, 2);
почему second?

2017-11-30 08:39 UTC, KSolovyev commented on src/main/java/seabattle/game/gamesession/GameSessionStatus.java
> +public enum GameSessionStatus {
http://gameprogrammingpatterns.com/state.html

не обязательно делать, как там написано, но прочтите

2017-11-30 08:39 UTC, KSolovyev commented on src/main/java/seabattle/game/field/Field.java
> +    private final Integer fieldSize = 10;
в ресурсы. Или по крайней мере в константы

2017-11-30 08:39 UTC, KSolovyev commented on src/main/java/seabattle/msgsystem/MsgShipPositionHandler.java
> +                    gameSession.getPlayer1().setShips(cast.getShips());
вот тут нужно валидировать положение кораблей. А то, если кто-то воткнет вертикальный четырехпалубник на 10, 10, второму игроку будет грустно

2017-11-30 08:41 UTC, KSolovyev requested changes
Самая большая проблема - с закрывающейся сессией.
Еще я хочу, чтобы вы после регистрации сразу логинили пользователя.
И почта вида 1@1.mail.ru должна проходить валидацию

2017-12-06 10:06 UTC, vla-parfenkov commented on src/main/java/seabattle/game/gamesession/GameSessionService.java
> +        Integer secondPlayerPosition = ThreadLocalRandom.current().nextInt(0, 2);
Потому что damaged - атакуемый, он ходит вторым.

2017-12-07 17:00 UTC, vla-parfenkov commented on src/main/java/seabattle/game/field/Field.java
> +                throw new IllegalArgumentException("Given position is already checked!");
Да, будем править)

2017-12-11 10:43 UTC, vla-parfenkov commented on src/main/java/seabattle/game/field/Field.java
> +                throw new IllegalArgumentException("Given position is already checked!");
Проблема была не в этом. Эту ошибку мы отлавливаем и шлем сообщение клиенту о том, что недопустимый ход.

2017-12-12 10:00 UTC, vla-parfenkov commented
Исправили замечания, будем на этой неделе дописывать бота и тесты на него.

2017-12-13 20:56 UTC, KSolovyev requested changes

2017-12-13 20:56 UTC, KSolovyev commented on src/main/java/seabattle/game/player/PlayerAI.java
> +public  final class PlayerAI extends Player {
Вот тут  Player (или   Participant) должен быть интерфейсом. От него должно быть два наследника: UserPlayer (Player) и AiPlayer (AiBot)

2017-12-13 20:56 UTC, KSolovyev commented on src/main/java/seabattle/game/player/PlayerAI.java
> +    public static List<Ship> generateShips() {
Эта функция очень длинная, сложная и нечитаемая. Надо разбить ее на более маленькие простые приватные функции. Правила здесь примерно такие: в функции должно быть  не более 15-20 строк и не более 2-3 уровней ветвления

2017-12-13 20:56 UTC, KSolovyev commented on src/main/java/seabattle/msgsystem/MsgShipPositionHandler.java
> +                    gameSession.getPlayer1().setShips(cast.getShips());
Положение кораблей надо все-таки валидировать

2017-12-13 20:58 UTC, KSolovyev commented on src/main/java/seabattle/msgsystem/MsgShipPositionHandler.java
> +                    gameSession.getPlayer1().setShips(cast.getShips());
А, вижу, сделали

2017-12-14 10:25 UTC, MikeGus commented on src/main/java/seabattle/game/player/PlayerAI.java
> +public  final class PlayerAI extends Player {
Исправлено

2017-12-14 10:25 UTC, MikeGus commented on src/main/java/seabattle/game/player/PlayerAI.java
> +    public static List<Ship> generateShips() {
Исправлено

2017-12-18 18:58 UTC, KSolovyev requested changes

2017-12-18 18:58 UTC, KSolovyev commented on src/main/java/seabattle/game/gamesession/GameSessionService.java
> +            GameSession gameSession = gameSessionReference.get();
а что игровая сессия может смениться в момент хода?

2017-12-18 19:03 UTC, MikeGus commented on src/main/java/seabattle/game/gamesession/GameSessionService.java
> +            GameSession gameSession = gameSessionReference.get();
Может перейти в новое состояние - состояние победы. В таком случае будет изменен класс объекта на GameSessionEndgame.

2017-12-18 19:08 UTC, MikeGus commented on src/main/java/seabattle/game/gamesession/GameSessionService.java
> +            GameSession gameSession = gameSessionReference.get();
Сделано для того, чтобы избавиться от свитча в свитче. Для каждого состояния сессии существует класс, переопределяющий методы интерфейса GameSession и бросающий исключения, если метод не может быть вызван данным состоянием.

2017-12-20 19:29 UTC, KSolovyev commented on src/main/java/seabattle/game/gamesession/GameSessionService.java
> +            GameSession gameSession = gameSessionReference.get();
Надо было внутрь GameSession положить AtomicReference на объект типа State (или SessionState). И методы делегировать. А так получается, что у вас сессия мутирует,а это не правда.

2017-12-21 13:47 UTC, KSolovyev commented
Скажите, когда мержить. Я больше не буду придираться

2017-12-21 15:35 UTC, vla-parfenkov commented
Ну в общем можно мерджить, ваше замечание про мутабельность игровой сессии исправлено. Сегодня пытался запилить многопоточку и таймауты, но нормально синхнронизировать не вышло, поэтому откатил до однопоточной, но рабочей версии.

2017-12-22 17:08 UTC, KSolovyev commented
ок

2017-12-22 17:08 UTC, KSolovyev approved these changes

2017-12-22 17:09 UTC, merged